<a href="https://colab.research.google.com/github/25wh1a05am/NASSCOM/blob/main/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


# ============================================================
# Task 1: Array Creation Shortcuts
# ============================================================

print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array with numbers from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers from 10 to 50 inclusive
arr1_4 = np.random.randint(10, 51, size=(5, 5))


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# ============================================================
# Task 2: Indexing and Slicing with Arrays
# ============================================================

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

d(4, 5))

# 3.1 Replace values less than 10 with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count even elements
even_count3_3 = np.sum(arr3_1 % 2 == 0)


print("\narr3_1:\n", arr3_1)
print("\narr3_2:\n", arr3_2)
print("\nNumber of even elements:", even_count3_3)


# ============================================================
# Task 4: Aggregation Functions
# ============================================================

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])


# 4.1 Sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Standard deviation of entire array
std4_4 = np.std(arr4_1)


print("\nSum:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum of each row:", max_rows4_3)
print("Standard deviation:", std4_4)


# ============================================================
# Task 5: Reshaping and Flattening
# ============================================================

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)


# 5.1 Reshape into 4x6
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into 2x3x4
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten back into 1D using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Also demonstrate flatten()
flattened_arr5_4_copy = reshaped_arr5_2.flatten()


print("\nOriginal array:")
print(arr5_1)

print("\nReshaped 4x6 array:")
print(reshaped_arr5_2)

print("\nReshaped 2x3x4 array:")
print(reshaped_arr5_3)

print("\nFlattened using ravel():")
print(flattened_arr5_4)

print("\nFlattened using flatten():")
print(flattened_arr5_4_copy)


# ============================================================
# Task 6: Broadcasting
# ============================================================

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10

vector = np.array([100, 200, 300])


# 6.1 Add scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add vector to every row
result6_2 = arr6_1 + vector


print("\nOriginal array:")
print(arr6_1)

print("\nAfter adding scalar:")
print(result6_1)

print("\nAfter adding vector:")
print(result6_2)


# ============================================================
# Task 7: Copying vs. Viewing Arrays
# ============================================================

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])


# 7.1 Create a view
view_arr7 = original_arr7[:]

# Modify first element of view
    [9, 10],
    [11, 12]
])


# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined array into 3 equal parts
part1, part2, part3 = np.vsplit(combined_arr8_3, 3)


print("\nVertical stack:")
print(vstack_arr8_1)

print("\nHorizontal stack:")
print(hstack_arr8_2)

print("\nCombined array:")
print(combined_arr8_3)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

print("\nPart 3:")
print(part3)


# ============================================================
# Task 9: Sorting and Searching
# ============================================================

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])


# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns
# axis=0 means sort vertically within each column
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find indices where value is 9
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of maximum value
max_idx9_4 = np.argmax(arr9_1)


print("\nOriginal arr9_1:")
print(arr9_1)

print("\nSorted arr9_1:")
print(sorted_arr9_1)

print("\nOriginal arr9_2d:")
print(arr9_2d)

print("\nColumns sorted:")
print(sorted_cols9_2)

print("\nIndex where value 9 is present:")
print(idx9_3)

print("\nIndex of maximum value:")
print(max_idx9_4)

print("\nMaximum value:")
print(arr9_1[max_idx9_4])


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n===================================")
print("NumPy Exercise Completed!")
print("===================================")

print("\nTask 1:")
print("arr1_1 shape:", arr1_1.shape)
print("arr1_2 shape:", arr1_2.shape)
print("arr1_3 shape:", arr1_3.shape)
print("arr1_4 shape:", arr1_4.shape)

print("\nTask 2:")
print("val2_1:", val2_1)
print("filtered_elements2_5:", filtered_elements2_5)

print("\nTask 3:")
print("Even count:", even_count3_3)

print("\nTask 4:")
print("Total sum:", sum4_1)
print("Column means:", mean_cols4_2)
print("Row maximums:", max_rows4_3)
print("Standard deviation:", std4_4)

print("\nTask 6:")
print("Scalar result:\n", result6_1)
print("Vector result:\n", result6_2)

print("\nTask 9:")
print("Sorted array:", sorted_arr9_1)
print("Index of 9:", idx9_3)
print("Index of maximum:", max_idx9_4)


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[10 23 43 49 22]
 [33 46 38 35 40]]

--- Task 2: Indexing and Slicing with Arrays ---

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---

arr3_1:
 [[15  4  4  8 15]
 [ 8 11  4  7 19]
 [ 3  4  8  3 12]
 [ 9 12 19  7  7]]

arr3_2:
 [[15  0  0  0 15]
 [ 0 11  0  0 19]
 [ 0  0  0  0 12]
 [ 0 12 19  0  0]]

Number of even elements: 9

--- Task 4: Aggregation Functions ---

Sum: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum of each row: [12 15 20]
Standard deviation: 5.2493385826745405

--- Task 5: Reshaping and Flatten

ValueError: array split does not result in an equal division

In [3]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


# ============================================================
# Task 1: Array Creation Shortcuts
# ============================================================

print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers
# between 10 and 50 inclusive
arr1_4 = np.random.randint(10, 51, size=(5, 5))


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# ============================================================
# Task 2: Indexing and Slicing with Arrays
# ============================================================

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


# 2.1 Extract element at row 2, column 3
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]


print("\nval2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


# ============================================================
# Task 3: Conditional Operations
# ============================================================

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))


# 3.1 Replace values less than 10 with 0
# Values >= 10 remain unchanged
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count how many elements are even
even_count3_3 = np.sum(arr3_1 % 2 == 0)


print("\narr3_1:")
print(arr3_1)

print("\narr3_2:")
print(arr3_2)

print("\neven_count3_3:", even_count3_3)


# ============================================================
# Task 4: Aggregation Functions
# ============================================================

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])


# 4.1 Calculate sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate mean of each column
# axis=0 means operate down the rows
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find maximum value in each row
# axis=1 means operate across the columns
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate standard deviation of entire array
std4_4 = np.std(arr4_1)


print("\nsum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


# ============================================================
# Task 5: Reshaping and Flattening
# ============================================================

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)


# 5.1 Reshape arr5_1 into a 4x6 array
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape arr5_1 into a 2x3x4 array
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten reshaped_arr5_2 using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Also use flatten() to compare
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()


print("\narr5_1:")
print(arr5_1)

print("\nreshaped_arr5_2:")
print(reshaped_arr5_2)

print("\nreshaped_arr5_3:")
print(reshaped_arr5_3)

print("\nflattened_arr5_4 using ravel():")
print(flattened_arr5_4)

print("\nUsing flatten():")
print(flattened_arr5_4_flatten)


# ============================================================
# Task 6: Broadcasting
# ============================================================

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10

vector = np.array([100, 200, 300])


# 6.1 Add scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add vector to each row
result6_2 = arr6_1 + vector


print("\narr6_1:")
print(arr6_1)

print("\nresult6_1:")
print(result6_1)

print("\nresult6_2:")
print(result6_2)


# ============================================================
# Task 7: Copying vs. Viewing Arrays
# ============================================================

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])


# 7.1 Create a view using slicing
view_arr7 = original_arr7[:]

# Modify first element of the view
view_arr7[0] = 99


print("\nAfter modifying view_arr7:")
print("view_arr7:", view_arr7)
print("original_arr7:", original_arr7)


# 7.2 Create an independent copy
copy_arr7 = original_arr7.copy()

# Modify last element of copy
copy_arr7[-1] = 0


print("\nAfter modifying copy_arr7:")
print("copy_arr7:", copy_arr7)
print("original_arr7:", original_arr7)


# ============================================================
# Task 8: Stacking and Splitting Arrays
# ============================================================

print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])


# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined_arr8_3 into 3 equal parts
part1, part2, part3 = np.vsplit(combined_arr8_3, 3)


print("\nvstack_arr8_1:")
print(vstack_arr8_1)

print("\nhstack_arr8_2:")
print(hstack_arr8_2)

print("\ncombined_arr8_3:")
print(combined_arr8_3)

print("\npart1:")
print(part1)

print("\npart2:")
print(part2)

print("\npart3:")
print(part3)


# ============================================================
# Task 9: Sorting and Searching
# ============================================================

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])


# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns
# axis=0 means each column is sorted independently
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find indices where value 9 is present
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of maximum value
max_idx9_4 = np.argmax(arr9_1)


print("\narr9_1:")
print(arr9_1)

print("\nsorted_arr9_1:")
print(sorted_arr9_1)

print("\narr9_2d:")
print(arr9_2d)

print("\nsorted_cols9_2:")
print(sorted_cols9_2)

print("\nidx9_3:")
print(idx9_3)

print("\nmax_idx9_4:")
print(max_idx9_4)

print("\nMaximum value:")
print(arr9_1[max_idx9_4])


# ============================================================
# FINAL OUTPUT
# ============================================================

print("\n===================================")
print("NumPy Exercise Completed!")
print("===================================")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[37 39 10 47 30]
 [24 42 16 44 24]]

--- Task 2: Indexing and Slicing with Arrays ---

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---

arr3_1:
[[14  2  2 10  1]
 [ 6  9  5 13 18]
 [ 1 14  9  3 10]
 [13 19 11 18 18]]

arr3_2:
[[14  0  0 10  0]
 [ 0  0  0 13 18]
 [ 0 14  0  0 10]
 [13 19 11 18 18]]

even_count3_3: 10

--- Task 4: Aggregation Functions ---

sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---

arr5_1:
[ 0  1  2  3  4  5

ValueError: array split does not result in an equal division

In [4]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


# ============================================================
# Task 1: Array Creation Shortcuts
# ============================================================

print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers from 10 to 50 inclusive
arr1_4 = np.random.randint(10, 51, size=(5, 5))


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# ============================================================
# Task 2: Indexing and Slicing with Arrays
# ============================================================

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


# 2.1 Extract element at row 2, column 3
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0, :]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]


print("\nval2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


# ============================================================
# Task 3: Conditional Operations
# ============================================================

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))


# 3.1 Replace values less than 10 with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count how many elements are even
even_count3_3 = np.sum(arr3_1 % 2 == 0)


print("\narr3_1:")
print(arr3_1)

print("\narr3_2:")
print(arr3_2)

print("\neven_count3_3:", even_count3_3)


# ============================================================
# Task 4: Aggregation Functions
# ============================================================

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])


# 4.1 Calculate sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate standard deviation
std4_4 = np.std(arr4_1)


print("\nsum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


# ============================================================
# Task 5: Reshaping and Flattening
# ============================================================

print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)


# 5.1 Reshape into 4x6
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into 2x3x4
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()

# Also demonstrate flatten()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()


print("\narr5_1:")
print(arr5_1)

print("\nreshaped_arr5_2:")
print(reshaped_arr5_2)

print("\nreshaped_arr5_3:")
print(reshaped_arr5_3)

print("\nflattened_arr5_4:")
print(flattened_arr5_4)

print("\nflatten() result:")
print(flattened_arr5_4_flatten)


# ============================================================
# Task 6: Broadcasting
# ============================================================

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10

vector = np.array([100, 200, 300])


# 6.1 Add scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add vector to each row
result6_2 = arr6_1 + vector


print("\narr6_1:")
print(arr6_1)

print("\nresult6_1:")
print(result6_1)

print("\nresult6_2:")
print(result6_2)


# ============================================================
# Task 7: Copying vs. Viewing Arrays
# ============================================================

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])


# 7.1 Create a view
view_arr7 = original_arr7[:]

# Modify first element of view
view_arr7[0] = 99


print("\nAfter modifying view_arr7:")
print("view_arr7:", view_arr7)
print("original_arr7:", original_arr7)


# 7.2 Create a copy
copy_arr7 = original_arr7.copy()

# Modify last element of copy
copy_arr7[-1] = 0


print("\nAfter modifying copy_arr7:")
print("copy_arr7:", copy_arr7)
print("original_arr7:", original_arr7)


# ============================================================
# Task 8: Stacking and Splitting Arrays
# ============================================================

print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])


# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined_arr8_3 into 3 parts
#
# combined_arr8_3 has 5 rows, so it cannot be divided
# into 3 equal parts using np.vsplit().
# np.array_split() allows unequal-sized parts.
part1, part2, part3 = np.array_split(combined_arr8_3, 3)


print("\nvstack_arr8_1:")
print(vstack_arr8_1)

print("\nhstack_arr8_2:")
print(hstack_arr8_2)

print("\ncombined_arr8_3:")
print(combined_arr8_3)

print("\npart1:")
print(part1)

print("\npart2:")
print(part2)

print("\npart3:")
print(part3)


# ============================================================
# Task 9: Sorting and Searching
# ============================================================

print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])


# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find indices where value 9 is present
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find index of maximum value
max_idx9_4 = np.argmax(arr9_1)


print("\narr9_1:")
print(arr9_1)

print("\nsorted_arr9_1:")
print(sorted_arr9_1)

print("\narr9_2d:")
print(arr9_2d)

print("\nsorted_cols9_2:")
print(sorted_cols9_2)

print("\nidx9_3:")
print(idx9_3)

print("\nmax_idx9_4:")
print(max_idx9_4)

print("\nMaximum value:")
print(arr9_1[max_idx9_4])


# ============================================================
# Final Output
# ============================================================

print("\n===================================")
print("NumPy Exercise Completed Successfully!")
print("===================================")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[47 33 12 20 16]
 [35 20 46 40 13]]

--- Task 2: Indexing and Slicing with Arrays ---

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---

arr3_1:
[[ 7  6 12 19  9]
 [ 7 15  6  6 15]
 [13  6 15 12 12]
 [ 5  2  2 18 20]]

arr3_2:
[[ 0  0 12 19  0]
 [ 0 15  0  0 15]
 [13  0 15 12 12]
 [ 0  0  0 18 20]]

even_count3_3: 11

--- Task 4: Aggregation Functions ---

sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---

arr5_1:
[ 0  1  2  3  4  5