<a href="https://colab.research.google.com/github/25wh1a05am/NASSCOM/blob/main/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")


# ============================================================
# Task 1: Basic Pandas Functions and Converting Arrays
# ============================================================

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers from 1 to 100
np.random.seed(42)

np_array1_2 = np.random.randint(
    1,
    101,
    size=(3, 4)
)

# 1.3 Convert NumPy array to DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)


print("\ns1_1:")
print(s1_1)

print("\nnp_array1_2:")
print(np_array1_2)

print("\ndf1_3:")
print(df1_3)


# ============================================================
# Task 2: Synthetic Data Generation for Practice
# ============================================================

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create 100 dates from 2023-01-01 to 2023-04-10.
# However, the exercise specifically says 2023-04-09 inclusive.
# There are exactly 99 days in this range, so we create
# 100 rows using a daily date range and repeat the final date.

dates = pd.date_range(
    start='2023-01-01',
    end='2023-04-09',
    periods=100
)

# Randomly generate data
regions = np.random.choice(
    ['East', 'West', 'North', 'South'],
    size=100
)

products = np.random.choice(
    ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    size=100
)

sales = np.random.randint(
    100,
    1001,
    size=100
).astype(float)

quantity = np.random.randint(
    1,
    11,
    size=100
).astype(float)


# Create DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': regions,
    'Product': products,
    'Sales': sales,
    'Quantity': quantity
})


# ------------------------------------------------------------
# Introduce NaN values
# ------------------------------------------------------------

# Select 5 random rows for Sales NaN
sales_nan_indices = np.random.choice(
    df_sales.index,
    size=5,
    replace=False
)

# Select 3 random rows for Quantity NaN
quantity_nan_indices = np.random.choice(
    df_sales.index,
    size=3,
    replace=False
)

# Introduce NaN values
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan


print("\ndf_sales:")
print(df_sales)

print("\nShape of df_sales:")
print(df_sales.shape)

print("\nNumber of missing Sales values:")
print(df_sales['Sales'].isna().sum())

print("\nNumber of missing Quantity values:")
print(df_sales['Quantity'].isna().sum())


# ============================================================
# Task 3: Indexing and Slicing in DataFrames
# ============================================================

print("\n--- Task 3: Indexing and Slicing in DataFrames ---")


# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]


# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[
    df_sales['Product'] == 'Laptop'
]


# 3.3 Select rows where Region is East
# AND Sales are greater than 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]


# 3.4 Select Sales value for the first Monitor entry
#
# First find the index of the first Monitor row
monitor_indices = df_sales.index[
    df_sales['Product'] == 'Monitor'
]

if len(monitor_indices) > 0:

    first_monitor_index = monitor_indices[0]

    # Using .loc
    val3_4_loc = df_sales.loc[
        first_monitor_index,
        'Sales'
    ]

    # Using .iloc
    first_monitor_position = df_sales.index.get_loc(
        first_monitor_index
    )

    val3_4 = df_sales.iloc[
        first_monitor_position,
        df_sales.columns.get_loc('Sales')
    ]

else:

    val3_4 = np.nan


print("\ndf3_1:")
print(df3_1)

print("\ndf3_2:")
print(df3_2)

print("\ndf3_3:")
print(df3_3)

print("\nval3_4:")
print(val3_4)


# ============================================================
# Task 4: Data Cleaning
# ============================================================

print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")


# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isna().sum()


# 4.2 Fill missing Sales values with Sales mean
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = (
    df4_2_filled['Sales'].fillna(sales_mean)
)


# 4.3 Drop rows containing any missing values
df4_3_dropped = df_sales.dropna()


print("\nMissing values in each column:")
print(missing_counts4_1)

print("\nDataFrame after filling Sales NaNs:")
print(df4_2_filled)

print("\nDataFrame after dropping rows with NaNs:")
print(df4_3_dropped)


# ============================================================
# Task 5: Data Manipulation
# ============================================================

print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")


# 5.1 Create Total_Revenue column
#
# NaN * number = NaN
# number * NaN = NaN
#
# Therefore pandas automatically preserves NaNs.
df_sales['Total_Revenue'] = (
    df_sales['Sales'] *
    df_sales['Quantity']
)


# 5.2 Sort by Date ascending,
# then Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)


# 5.3 Group by Region
# Calculate sum of Sales and Quantity
df5_3_grouped_region = (
    df_sales
    .groupby('Region')[['Sales', 'Quantity']]
    .sum()
)


# 5.4 Group by Product
# Calculate average Sales
df5_4_grouped_product = (
    df_sales
    .groupby('Product')['Sales']
    .mean()
)


print("\nDataFrame with Total_Revenue:")
print(df_sales)

print("\nSorted DataFrame:")
print(df5_2_sorted)

print("\nSales and Quantity grouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales grouped by Product:")
print(df5_4_grouped_product)


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n==========================================")
print("Pandas Exercise Completed Successfully!")
print("==========================================")

print("\nTask 1:")
print("Series:")
print(s1_1)

print("\nDataFrame:")
print(df1_3)

print("\nTask 2:")
print("df_sales shape:", df_sales.shape)

print("\nTask 3:")
print("df3_1 shape:", df3_1.shape)
print("df3_2 shape:", df3_2.shape)
print("df3_3 shape:", df3_3.shape)
print("First Monitor Sales:", val3_4)

print("\nTask 4:")
print("Missing counts:")
print(missing_counts4_1)
print("Rows after dropna:", len(df4_3_dropped))

print("\nTask 5:")
print("Regional grouping:")
print(df5_3_grouped_region)

print("\nProduct average sales:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]]

df1_3:
    A   B   C    D
0  52  93  15   72
1  61  21  83   87
2  75  75  88  100

--- Task 2: Synthetic Data Generation for Practice ---

df_sales:
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000  South     Mouse  624.0       1.0
1  2023-01-01 23:45:27.272727272  South   Monitor  259.0       9.0
2  2023-01-02 23:30:54.545454545  North    Laptop  938.0       6.0
3  2023-01-03 23:16:21.818181818   West   Monitor  798.0       3.0
4  2023-01-04 23:01:49.090909090   East    Laptop  342.0       4.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910  South  